// This is a Automatically Generated File
#include "idt.h"

extern void __attribute__((cdecl)) ISR0();
extern void __attribute__((cdecl)) ISR1();
extern void __attribute__((cdecl)) ISR2();
extern void __attribute__((cdecl)) ISR3();
extern void __attribute__((cdecl)) ISR4();
extern void __attribute__((cdecl)) ISR5();
extern void __attribute__((cdecl)) ISR6();
extern void __attribute__((cdecl)) ISR7();
extern void __attribute__((cdecl)) ISR8();
extern void __attribute__((cdecl)) ISR9();
extern void __attribute__((cdecl)) ISR10();
extern void __attribute__((cdecl)) ISR11();
extern void __attribute__((cdecl)) ISR12();
extern void __attribute__((cdecl)) ISR13();
extern void __attribute__((cdecl)) ISR14();
extern void __attribute__((cdecl)) ISR15();
extern void __attribute__((cdecl)) ISR16();
extern void __attribute__((cdecl)) ISR17();
extern void __attribute__((cdecl)) ISR18();
extern void __attribute__((cdecl)) ISR19();
extern void __attribute__((cdecl)) ISR20();
extern void __attribute__((cdecl)) ISR21();
extern void __attribute__((cdecl)) ISR22();
extern void __attribute__((cdecl)) ISR23();
extern void __attribute__((cdecl)) ISR24();
extern void __attribute__((cdecl)) ISR25();
extern void __attribute__((cdecl)) ISR26();
extern void __attribute__((cdecl)) ISR27();
extern void __attribute__((cdecl)) ISR28();
extern void __attribute__((cdecl)) ISR29();
extern void __attribute__((cdecl)) ISR30();
extern void __attribute__((cdecl)) ISR31();
extern void __attribute__((cdecl)) ISR32();
extern void __attribute__((cdecl)) ISR33();
extern void __attribute__((cdecl)) ISR34();
extern void __attribute__((cdecl)) ISR35();
extern void __attribute__((cdecl)) ISR36();
extern void __attribute__((cdecl)) ISR37();
extern void __attribute__((cdecl)) ISR38();
extern void __attribute__((cdecl)) ISR39();
extern void __attribute__((cdecl)) ISR40();
extern void __attribute__((cdecl)) ISR41();
extern void __attribute__((cdecl)) ISR42();
extern void __attribute__((cdecl)) ISR43();
extern void __attribute__((cdecl)) ISR44();
extern void __attribute__((cdecl)) ISR45();
extern void __attribute__((cdecl)) ISR46();
extern void __attribute__((cdecl)) ISR47();
extern void __attribute__((cdecl)) ISR48();
extern void __attribute__((cdecl)) ISR49();
extern void __attribute__((cdecl)) ISR50();
extern void __attribute__((cdecl)) ISR51();
extern void __attribute__((cdecl)) ISR52();
extern void __attribute__((cdecl)) ISR53();
extern void __attribute__((cdecl)) ISR54();
extern void __attribute__((cdecl)) ISR55();
extern void __attribute__((cdecl)) ISR56();
extern void __attribute__((cdecl)) ISR57();
extern void __attribute__((cdecl)) ISR58();
extern void __attribute__((cdecl)) ISR59();
extern void __attribute__((cdecl)) ISR60();
extern void __attribute__((cdecl)) ISR61();
extern void __attribute__((cdecl)) ISR62();
extern void __attribute__((cdecl)) ISR63();
extern void __attribute__((cdecl)) ISR64();
extern void __attribute__((cdecl)) ISR65();
extern void __attribute__((cdecl)) ISR66();
extern void __attribute__((cdecl)) ISR67();
extern void __attribute__((cdecl)) ISR68();
extern void __attribute__((cdecl)) ISR69();
extern void __attribute__((cdecl)) ISR70();
extern void __attribute__((cdecl)) ISR71();
extern void __attribute__((cdecl)) ISR72();
extern void __attribute__((cdecl)) ISR73();
extern void __attribute__((cdecl)) ISR74();
extern void __attribute__((cdecl)) ISR75();
extern void __attribute__((cdecl)) ISR76();
extern void __attribute__((cdecl)) ISR77();
extern void __attribute__((cdecl)) ISR78();
extern void __attribute__((cdecl)) ISR79();
extern void __attribute__((cdecl)) ISR80();
extern void __attribute__((cdecl)) ISR81();
extern void __attribute__((cdecl)) ISR82();
extern void __attribute__((cdecl)) ISR83();
extern void __attribute__((cdecl)) ISR84();
extern void __attribute__((cdecl)) ISR85();
extern void __attribute__((cdecl)) ISR86();
extern void __attribute__((cdecl)) ISR87();
extern void __attribute__((cdecl)) ISR88();
extern void __attribute__((cdecl)) ISR89();
extern void __attribute__((cdecl)) ISR90();
extern void __attribute__((cdecl)) ISR91();
extern void __attribute__((cdecl)) ISR92();
extern void __attribute__((cdecl)) ISR93();
extern void __attribute__((cdecl)) ISR94();
extern void __attribute__((cdecl)) ISR95();
extern void __attribute__((cdecl)) ISR96();
extern void __attribute__((cdecl)) ISR97();
extern void __attribute__((cdecl)) ISR98();
extern void __attribute__((cdecl)) ISR99();
extern void __attribute__((cdecl)) ISR100();
extern void __attribute__((cdecl)) ISR101();
extern void __attribute__((cdecl)) ISR102();
extern void __attribute__((cdecl)) ISR103();
extern void __attribute__((cdecl)) ISR104();
extern void __attribute__((cdecl)) ISR105();
extern void __attribute__((cdecl)) ISR106();
extern void __attribute__((cdecl)) ISR107();
extern void __attribute__((cdecl)) ISR108();
extern void __attribute__((cdecl)) ISR109();
extern void __attribute__((cdecl)) ISR110();
extern void __attribute__((cdecl)) ISR111();
extern void __attribute__((cdecl)) ISR112();
extern void __attribute__((cdecl)) ISR113();
extern void __attribute__((cdecl)) ISR114();
extern void __attribute__((cdecl)) ISR115();
extern void __attribute__((cdecl)) ISR116();
extern void __attribute__((cdecl)) ISR117();
extern void __attribute__((cdecl)) ISR118();
extern void __attribute__((cdecl)) ISR119();
extern void __attribute__((cdecl)) ISR120();
extern void __attribute__((cdecl)) ISR121();
extern void __attribute__((cdecl)) ISR122();
extern void __attribute__((cdecl)) ISR123();
extern void __attribute__((cdecl)) ISR124();
extern void __attribute__((cdecl)) ISR125();
extern void __attribute__((cdecl)) ISR126();
extern void __attribute__((cdecl)) ISR127();
extern void __attribute__((cdecl)) ISR128();
extern void __attribute__((cdecl)) ISR129();
extern void __attribute__((cdecl)) ISR130();
extern void __attribute__((cdecl)) ISR131();
extern void __attribute__((cdecl)) ISR132();
extern void __attribute__((cdecl)) ISR133();
extern void __attribute__((cdecl)) ISR134();
extern void __attribute__((cdecl)) ISR135();
extern void __attribute__((cdecl)) ISR136();
extern void __attribute__((cdecl)) ISR137();
extern void __attribute__((cdecl)) ISR138();
extern void __attribute__((cdecl)) ISR139();
extern void __attribute__((cdecl)) ISR140();
extern void __attribute__((cdecl)) ISR141();
extern void __attribute__((cdecl)) ISR142();
extern void __attribute__((cdecl)) ISR143();
extern void __attribute__((cdecl)) ISR144();
extern void __attribute__((cdecl)) ISR145();
extern void __attribute__((cdecl)) ISR146();
extern void __attribute__((cdecl)) ISR147();
extern void __attribute__((cdecl)) ISR148();
extern void __attribute__((cdecl)) ISR149();
extern void __attribute__((cdecl)) ISR150();
extern void __attribute__((cdecl)) ISR151();
extern void __attribute__((cdecl)) ISR152();
extern void __attribute__((cdecl)) ISR153();
extern void __attribute__((cdecl)) ISR154();
extern void __attribute__((cdecl)) ISR155();
extern void __attribute__((cdecl)) ISR156();
extern void __attribute__((cdecl)) ISR157();
extern void __attribute__((cdecl)) ISR158();
extern void __attribute__((cdecl)) ISR159();
extern void __attribute__((cdecl)) ISR160();
extern void __attribute__((cdecl)) ISR161();
extern void __attribute__((cdecl)) ISR162();
extern void __attribute__((cdecl)) ISR163();
extern void __attribute__((cdecl)) ISR164();
extern void __attribute__((cdecl)) ISR165();
extern void __attribute__((cdecl)) ISR166();
extern void __attribute__((cdecl)) ISR167();
extern void __attribute__((cdecl)) ISR168();
extern void __attribute__((cdecl)) ISR169();
extern void __attribute__((cdecl)) ISR170();
extern void __attribute__((cdecl)) ISR171();
extern void __attribute__((cdecl)) ISR172();
extern void __attribute__((cdecl)) ISR173();
extern void __attribute__((cdecl)) ISR174();
extern void __attribute__((cdecl)) ISR175();
extern void __attribute__((cdecl)) ISR176();
extern void __attribute__((cdecl)) ISR177();
extern void __attribute__((cdecl)) ISR178();
extern void __attribute__((cdecl)) ISR179();
extern void __attribute__((cdecl)) ISR180();
extern void __attribute__((cdecl)) ISR181();
extern void __attribute__((cdecl)) ISR182();
extern void __attribute__((cdecl)) ISR183();
extern void __attribute__((cdecl)) ISR184();
extern void __attribute__((cdecl)) ISR185();
extern void __attribute__((cdecl)) ISR186();
extern void __attribute__((cdecl)) ISR187();
extern void __attribute__((cdecl)) ISR188();
extern void __attribute__((cdecl)) ISR189();
extern void __attribute__((cdecl)) ISR190();
extern void __attribute__((cdecl)) ISR191();
extern void __attribute__((cdecl)) ISR192();
extern void __attribute__((cdecl)) ISR193();
extern void __attribute__((cdecl)) ISR194();
extern void __attribute__((cdecl)) ISR195();
extern void __attribute__((cdecl)) ISR196();
extern void __attribute__((cdecl)) ISR197();
extern void __attribute__((cdecl)) ISR198();
extern void __attribute__((cdecl)) ISR199();
extern void __attribute__((cdecl)) ISR200();
extern void __attribute__((cdecl)) ISR201();
extern void __attribute__((cdecl)) ISR202();
extern void __attribute__((cdecl)) ISR203();
extern void __attribute__((cdecl)) ISR204();
extern void __attribute__((cdecl)) ISR205();
extern void __attribute__((cdecl)) ISR206();
extern void __attribute__((cdecl)) ISR207();
extern void __attribute__((cdecl)) ISR208();
extern void __attribute__((cdecl)) ISR209();
extern void __attribute__((cdecl)) ISR210();
extern void __attribute__((cdecl)) ISR211();
extern void __attribute__((cdecl)) ISR212();
extern void __attribute__((cdecl)) ISR213();
extern void __attribute__((cdecl)) ISR214();
extern void __attribute__((cdecl)) ISR215();
extern void __attribute__((cdecl)) ISR216();
extern void __attribute__((cdecl)) ISR217();
extern void __attribute__((cdecl)) ISR218();
extern void __attribute__((cdecl)) ISR219();
extern void __attribute__((cdecl)) ISR220();
extern void __attribute__((cdecl)) ISR221();
extern void __attribute__((cdecl)) ISR222();
extern void __attribute__((cdecl)) ISR223();
extern void __attribute__((cdecl)) ISR224();
extern void __attribute__((cdecl)) ISR225();
extern void __attribute__((cdecl)) ISR226();
extern void __attribute__((cdecl)) ISR227();
extern void __attribute__((cdecl)) ISR228();
extern void __attribute__((cdecl)) ISR229();
extern void __attribute__((cdecl)) ISR230();
extern void __attribute__((cdecl)) ISR231();
extern void __attribute__((cdecl)) ISR232();
extern void __attribute__((cdecl)) ISR233();
extern void __attribute__((cdecl)) ISR234();
extern void __attribute__((cdecl)) ISR235();
extern void __attribute__((cdecl)) ISR236();
extern void __attribute__((cdecl)) ISR237();
extern void __attribute__((cdecl)) ISR238();
extern void __attribute__((cdecl)) ISR239();
extern void __attribute__((cdecl)) ISR240();
extern void __attribute__((cdecl)) ISR241();
extern void __attribute__((cdecl)) ISR242();
extern void __attribute__((cdecl)) ISR243();
extern void __attribute__((cdecl)) ISR244();
extern void __attribute__((cdecl)) ISR245();
extern void __attribute__((cdecl)) ISR246();
extern void __attribute__((cdecl)) ISR247();
extern void __attribute__((cdecl)) ISR248();
extern void __attribute__((cdecl)) ISR249();
extern void __attribute__((cdecl)) ISR250();
extern void __attribute__((cdecl)) ISR251();
extern void __attribute__((cdecl)) ISR252();
extern void __attribute__((cdecl)) ISR253();
extern void __attribute__((cdecl)) ISR254();
extern void __attribute__((cdecl)) ISR255();

void ISR_initialize_gates() {
	IDT_set_gate(0, ISR0, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(1, ISR1, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(2, ISR2, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(3, ISR3, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(4, ISR4, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(5, ISR5, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(6, ISR6, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(7, ISR7, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(8, ISR8, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(9, ISR9, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(10, ISR10, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(11, ISR11, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(12, ISR12, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(13, ISR13, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(14, ISR14, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(15, ISR15, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(16, ISR16, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(17, ISR17, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(18, ISR18, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(19, ISR19, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(20, ISR20, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(21, ISR21, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(22, ISR22, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(23, ISR23, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(24, ISR24, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(25, ISR25, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(26, ISR26, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(27, ISR27, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(28, ISR28, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(29, ISR29, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(30, ISR30, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(31, ISR31, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(32, ISR32, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(33, ISR33, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(34, ISR34, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(35, ISR35, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(36, ISR36, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(37, ISR37, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(38, ISR38, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(39, ISR39, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(40, ISR40, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(41, ISR41, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(42, ISR42, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(43, ISR43, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(44, ISR44, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(45, ISR45, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(46, ISR46, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(47, ISR47, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(48, ISR48, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(49, ISR49, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(50, ISR50, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(51, ISR51, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(52, ISR52, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(53, ISR53, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(54, ISR54, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(55, ISR55, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(56, ISR56, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(57, ISR57, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(58, ISR58, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(59, ISR59, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(60, ISR60, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(61, ISR61, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(62, ISR62, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(63, ISR63, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(64, ISR64, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(65, ISR65, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(66, ISR66, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(67, ISR67, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(68, ISR68, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(69, ISR69, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(70, ISR70, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(71, ISR71, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(72, ISR72, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(73, ISR73, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(74, ISR74, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(75, ISR75, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(76, ISR76, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(77, ISR77, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(78, ISR78, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(79, ISR79, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(80, ISR80, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(81, ISR81, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(82, ISR82, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(83, ISR83, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(84, ISR84, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(85, ISR85, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(86, ISR86, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(87, ISR87, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(88, ISR88, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(89, ISR89, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(90, ISR90, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(91, ISR91, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(92, ISR92, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(93, ISR93, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(94, ISR94, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(95, ISR95, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(96, ISR96, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(97, ISR97, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(98, ISR98, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(99, ISR99, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(100, ISR100, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(101, ISR101, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(102, ISR102, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(103, ISR103, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(104, ISR104, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(105, ISR105, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(106, ISR106, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(107, ISR107, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(108, ISR108, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(109, ISR109, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(110, ISR110, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(111, ISR111, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(112, ISR112, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(113, ISR113, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(114, ISR114, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(115, ISR115, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(116, ISR116, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(117, ISR117, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(118, ISR118, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(119, ISR119, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(120, ISR120, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(121, ISR121, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(122, ISR122, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(123, ISR123, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(124, ISR124, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(125, ISR125, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(126, ISR126, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(127, ISR127, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(128, ISR128, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(129, ISR129, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(130, ISR130, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(131, ISR131, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(132, ISR132, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(133, ISR133, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(134, ISR134, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(135, ISR135, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(136, ISR136, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(137, ISR137, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(138, ISR138, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(139, ISR139, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(140, ISR140, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(141, ISR141, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(142, ISR142, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(143, ISR143, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(144, ISR144, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(145, ISR145, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(146, ISR146, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(147, ISR147, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(148, ISR148, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(149, ISR149, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(150, ISR150, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(151, ISR151, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(152, ISR152, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(153, ISR153, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(154, ISR154, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(155, ISR155, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(156, ISR156, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(157, ISR157, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(158, ISR158, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(159, ISR159, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(160, ISR160, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(161, ISR161, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(162, ISR162, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(163, ISR163, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(164, ISR164, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(165, ISR165, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(166, ISR166, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(167, ISR167, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(168, ISR168, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(169, ISR169, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(170, ISR170, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(171, ISR171, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(172, ISR172, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(173, ISR173, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(174, ISR174, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(175, ISR175, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(176, ISR176, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(177, ISR177, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(178, ISR178, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(179, ISR179, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(180, ISR180, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(181, ISR181, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(182, ISR182, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(183, ISR183, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(184, ISR184, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(185, ISR185, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(186, ISR186, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(187, ISR187, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(188, ISR188, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(189, ISR189, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(190, ISR190, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(191, ISR191, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(192, ISR192, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(193, ISR193, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(194, ISR194, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(195, ISR195, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(196, ISR196, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(197, ISR197, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(198, ISR198, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(199, ISR199, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(200, ISR200, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(201, ISR201, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(202, ISR202, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(203, ISR203, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(204, ISR204, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(205, ISR205, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(206, ISR206, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(207, ISR207, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(208, ISR208, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(209, ISR209, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(210, ISR210, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(211, ISR211, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(212, ISR212, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(213, ISR213, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(214, ISR214, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(215, ISR215, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(216, ISR216, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(217, ISR217, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(218, ISR218, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(219, ISR219, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(220, ISR220, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(221, ISR221, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(222, ISR222, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(223, ISR223, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(224, ISR224, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(225, ISR225, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(226, ISR226, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(227, ISR227, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(228, ISR228, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(229, ISR229, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(230, ISR230, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(231, ISR231, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(232, ISR232, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(233, ISR233, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(234, ISR234, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(235, ISR235, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(236, ISR236, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(237, ISR237, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(238, ISR238, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(239, ISR239, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(240, ISR240, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(241, ISR241, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(242, ISR242, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(243, ISR243, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(244, ISR244, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(245, ISR245, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(246, ISR246, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(247, ISR247, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(248, ISR248, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(249, ISR249, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(250, ISR250, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(251, ISR251, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(252, ISR252, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(253, ISR253, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(254, ISR254, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
	IDT_set_gate(255, ISR255, CODE_SEGMENT, IDT_FLAG_GATE_32_INT | IDT_FLAG_RING_0);
}